# Generated by Django 3.2.11 on 2022-01-19 18:00

from django.db import migrations, models
import django.db.models.deletion
import pulp_ansible.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_rbaccontentguard_options'),
        ('ansible', '0037_gitremote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRedirectContentGuard',
            fields=[
                ('contentguard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ansible_contentredirectcontentguard', serialize=False, to='core.contentguard')),
                ('shared_secret', models.BinaryField(default=pulp_ansible.app.models._gen_secret, max_length=32)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.contentguard',),
        ),
    ]
